// Machine-readable API error codes. UI text is localized by clients.
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  ORIGIN_NOT_ALLOWED: 'ORIGIN_NOT_ALLOWED',
  SERVER_MISCONFIGURED: 'SERVER_MISCONFIGURED',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ASSET: 'DUPLICATE_ASSET',
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  UPLOAD_OBJECT_MISSING: 'UPLOAD_OBJECT_MISSING',
  UPLOAD_OBJECT_INVALID: 'UPLOAD_OBJECT_INVALID',
  UPLOAD_RESULT_GONE: 'UPLOAD_RESULT_GONE',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_NOT_TRASHED: 'ASSET_NOT_TRASHED',
  REPAIR_SOURCE_UNUSABLE: 'REPAIR_SOURCE_UNUSABLE',
  ASSET_TRASHED: 'ASSET_TRASHED',
  ALBUM_NOT_FOUND: 'ALBUM_NOT_FOUND',
  SHARE_NOT_FOUND: 'SHARE_NOT_FOUND',
  SHARE_UNAVAILABLE: 'SHARE_UNAVAILABLE',
  LIBRARY_NOT_EMPTY: 'LIBRARY_NOT_EMPTY',
  INTERNAL: 'INTERNAL',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
